<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Ajuda</h1>
</div>
<div class="my-4 w-100" id="" width="900" height="380">
    <div class="list-group">
        <div class="jumbotron">
            <h4>Modelo Beta</h4>
            <p>Algumas funcionalidades podem ainda não estar ativas.</p>
        </div>
    </div>
</div>
