<!-- Painel formulário -->
<div class="register-panel">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <form id="formUsuario" action="site/usuario/save" method="post">
                    <div class="row">
                        <div class="col-12 col-lg-7 register-container">
                            <h4>Cadastrar Usuário</h4>
                            <hr>
                            <div class="toast-message" role="alert"></div>
                            <div class="form-row">
                                <div class="form-group col-lg-12">
                                    <label for="tipo-usuario">Tipo de usuário:</label>
                                    <select class="form-control" id="tipo-usuario" name="fkTipoUsuario">
                                        <option value="1">Administrador</option>
                                        <option value="2">Atendente</option>
                                        <option value="3">Cliente</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-lg-6">
                                    <label for="nome">Nome completo:</label>
                                    <input type="text" class="form-control" id="nome" name="nome" autofocus required>
                                </div>
                                <div class="form-group col-lg-6">
                                    <label for="username">Usuário:</label>
                                    <input type="text" class="form-control" id="username" name="usuario" placeholder="(min 6 caracteres)" required>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-lg-6">
                                    <label for="password">Senha:</label>
                                    <input type="password" class="form-control" id="password" name="senha" value="" placeholder="(min 6 caracteres)" required>
                                </div>
                                <div class="form-group col-lg-6">
                                    <label for="repeat-password">Confirme sua senha:</label>
                                    <input type="password" class="form-control" id="repeat-password" name="confirmarSenha" value="" required>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-12">
                                    <label for="email">Email:</label>
                                    <input type="email" class="form-control" id="email" name="email" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-lg-1">
                        </div>
                        <div class="col-12 col-lg-4 register-container">
                            <h4>Não sou um rôbo</h4>
                            <hr>
                            <div class="form-row">
                                <div class="form-group col-lg-12 text-center">
                                    <img class="img-fluid img-thumbnail mx-auto" src="<?= $this->captcha->oCaptchaBuilder->inline(); ?>">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-lg-12">
                                    <label for="phrase">Insira os caracteres exibidos na imagem acima:</label>
                                    <input type="text" class="form-control" id="phrase" name="phrase" maxlength="5" required>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-lg-12">
                                    <div class="form-check">
                                        <input type="checkbox" class="form-check-input" id="terms-check" name="termsCheck" value="1" required>
                                        <label class="form-check-label" for="terms-check"> Li e concordo com os <a href="#">termos de uso</a>.</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-lg-12 text-center">
                                    <button type="submit" class="btn btn-primary">Registrar</button>
                                    <button type="reset" class="btn btn-default">&nbsp;&nbsp; Limpar &nbsp;&nbsp;</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>