<!-- Banners do tipo slider -->
<div id="myCarousel" class="carousel slide heading-slider" data-ride="carousel">
    <div id="starting-slider" class="owl-carousel owl-theme">
        <div class="item">
            <div class="slider-1">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                            <div class="slider-inner-text">
                                <h1>Profissionalismo</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis illum dignissimos tempore ad, eos sint ullam </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="item">
            <div class="slider-2">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                            <div class="slider-inner-text">
                                <h1>Respeito</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis illum dignissimos tempore ad, eos sint ullam </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="item">
            <div class="slider-3">
                <div class="slider-inner">
                    <div class="container">
                        <div class="row">
                            <div class="slider-inner-text">
                                <h1>Responsabilidade</h1>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis illum dignissimos tempore ad, eos sint ullam </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>