<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <img src="img/logo.png" class="" height="50px" width="50px" border="0" alt="Logo - Fonte: https://www.iconfinder.com/icons/462999/chat_dialogue_message_bubbles_online_support_icon">
                <span style="vertical-align:middle" class="h2 text-info">&nbsp;Sistema de Atendimento Básico</span>
            </div>
        </div>
    </div>
</div>
<div class="my-4 w-100" id="" width="900" height="380">
    <div class="list-group">
        <div class="jumbotron">
            <h2>Bem vindo <?= $_SESSION['loggedUserName']; ?></h2>
            <h4>Modelo Beta</h4>
            <p>Algumas funcionalidades podem ainda não estar ativas.</p>
        </div>
    </div>
</div>