<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <title><?= isset($this->sTitle) ? $this->sTitle : ''; ?></title>
        <base href="<?= APP_ROOT; ?>">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta lang="pt-br">
        <meta name="description" content="<?= isset($this->sDescription) ? $this->sDescription : ''; ?>">
        <meta name="keywords" content="<?= isset($this->sKeywords) ? $this->sDescription : ''; ?>">
        <meta name="robots" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="author" content="Jonatan Noronha Reginato">
        <link rel="icon" type="image/x-icon" href="img/favicon.ico">
        <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="css/dashboard.css">
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
                <a class="navbar-brand" href="atendimento/home/index">Sistema de Atendimento Básico</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto"></ul>
                    <div class="form-inline mt-2 mt-md-0">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span data-feather="mail"></span>
                                    Chamados
                                </a>
                                <div class="dropdown-menu" aria-labelledby="dropdown01">
                                    <?php if ($_SESSION['loggedUserType'] === ADMINISTRADOR) : ?>
                                        <a class="dropdown-item" href="atendimento/chamado/listar/novos">Novos Chamados</a>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['loggedUserType'] !== CLIENTE) : ?>
                                        <a class="dropdown-item" href="atendimento/chamado/listar/atribuidos">Chamados Atribuídos</a>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['loggedUserType'] === CLIENTE) : ?>
                                        <a class="dropdown-item" href="atendimento/chamado/abrir">Abrir Chamado</a>
                                        <a class="dropdown-item" href="atendimento/chamado/listar/abertos">Chamados em Aberto</a>
                                    <?php endif; ?>
                                    <a class="dropdown-item" href="atendimento/chamado/listar/concluidos">Chamados Concluídos</a>
                                    <a class="dropdown-item" href="atendimento/chamado/listar">Todos os Chamados</a>
                                </div>
                            </li>
                            <?php if ($_SESSION['loggedUserType'] === ADMINISTRADOR) : ?>
                                <li class="nav-item">
                                    <a class="nav-link" href="atendimento/clientes/index">
                                        <span data-feather="users"></span>
                                        Clientes
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($_SESSION['loggedUserType'] !== CLIENTE) : ?>
                                <li class="nav-item">
                                    <a class="nav-link" href="atendimento/relatorio/index">
                                        <span data-feather="bar-chart-2"></span>
                                        Relatórios
                                    </a>
                                </li>
                            <?php endif; ?>
                            <li class="nav-item">
                                <a class="nav-link" href="atendimento/configuracao/index">
                                    <span data-feather="settings"></span>
                                    Configurações
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="atendimento/ajuda/index">
                                    <span data-feather="help-circle"></span>
                                    Ajuda
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="atendimento/home/logout">
                                    <span data-feather="log-out"></span>
                                    Sair
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container-fluid">
            <div class="row">
                <nav class="col-lg-2 d-none d-lg-block bg-light sidebar">
                    <div class="sidebar-sticky">
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link active" href="atendimento/home/index">
                                    <span data-feather="home"></span>
                                    Home <span class="sr-only">(current)</span>
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link" href="#" id="dropdown02" data-toggle="dropdown"  aria-haspopup="true" aria-expanded="false">
                                    <span data-feather="mail"></span>
                                    Chamados
                                </a>
                                <div class="dropdown-menu" aria-labelledby="dropdown02">
                                    <?php if ($_SESSION['loggedUserType'] === ADMINISTRADOR) : ?>
                                        <a class="dropdown-item" href="atendimento/chamado/listar/novos">Novos Chamados</a>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['loggedUserType'] !== CLIENTE) : ?>
                                        <a class="dropdown-item" href="atendimento/chamado/listar/atribuidos">Chamados Atribuídos</a>
                                    <?php endif; ?>
                                    <?php if ($_SESSION['loggedUserType'] === CLIENTE) : ?>
                                        <a class="dropdown-item" href="atendimento/chamado/abrir">Abrir Chamado</a>
                                        <a class="dropdown-item" href="atendimento/chamado/listar/abertos">Chamados em Aberto</a>
                                    <?php endif; ?>
                                    <a class="dropdown-item" href="atendimento/chamado/listar/concluidos">Chamados Concluídos</a>
                                    <a class="dropdown-item" href="atendimento/chamado/listar">Todos os Chamados</a>
                                </div>
                            </li>
                            <?php if ($_SESSION['loggedUserType'] === ADMINISTRADOR) : ?>
                                <li class="nav-item">
                                    <a class="nav-link" href="atendimento/clientes/index">
                                        <span data-feather="users"></span>
                                        Clientes
                                    </a>
                                </li>
                            <?php endif; ?>
                            <?php if ($_SESSION['loggedUserType'] !== CLIENTE) : ?>
                            <li class="nav-item">
                                <a class="nav-link" href="atendimento/relatorio/index">
                                    <span data-feather="bar-chart-2"></span>
                                    Relatórios
                                </a>
                            </li>
                            <?php endif; ?>
                            <li class="nav-item">
                                <a class="nav-link" href="atendimento/configuracao/index">
                                    <span data-feather="settings"></span>
                                    Configurações
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="atendimento/ajuda/index">
                                    <span data-feather="help-circle"></span>
                                    Ajuda
                                </a>
                            </li>
                        </ul>
                        <?php if ($_SESSION['loggedUserType'] !== CLIENTE) : ?>
                            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                                <span>Relatórios salvos</span>
                                <a class="d-flex align-items-center text-muted" href="atendimento/relatorio/index">
                                    <span data-feather="plus-circle"></span>
                                </a>
                            </h6>
                            <ul class="nav flex-column mb-2">
                                <li class="nav-item">
                                    <a class="nav-link" href="atendimento/relatorio/index">
                                        <span data-feather="file-text"></span>
                                        Neste mês
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="atendimento/relatorio/index">
                                        <span data-feather="file-text"></span>
                                        Último trimestre
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="atendimento/relatorio/index">
                                        <span data-feather="file-text"></span>
                                        Último semestre
                                    </a>
                                </li>
                            </ul>
                        <?php endif; ?>
                    </div>
                </nav>
                <main role="main" class="col-lg-9 ml-sm-auto col-lg-10 px-4">
                    <?php $this->render(); ?>
                </main>
            </div>
        </div>
        <script type="text/javascript" src="js/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/jquery.min.js"><\/script>');</script>
        <script type="text/javascript" src="js/popper.min.js"></script>
        <script type="text/javascript" src="js/bootstrap.min.js"></script>
        <script type="text/javascript" src="js/feather.min.js"></script>
        <script>
            feather.replace();
        </script>
        <script type="text/javascript" src="js/application.js"></script>
        <script>
            $(function()
            {
                onSubmitForm('#novoChamado');
                onSubmitForm('#atribuirChamado', true);
                onSubmitForm('#enviaMensagemChamado', true);
            });
        </script>
    </body>
</html>