<!DOCTYPE html>
<html>
    <head>
        <title>Erro 404</title>
        <base href="<?= APP_ROOT; ?>">
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta lang="pt-br">
        <meta name="description" content="<?= isset($this->sDescription) ? $this->sDescription : ''; ?>">
        <meta name="keywords" content="<?= isset($this->sKeywords) ? $this->sDescription : ''; ?>">
        <meta name="robots" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="icon" type="image/x-icon" href="img/favicon.ico">
    </head>
    <body>
        <?= ERROR; ?>
    </body>
</html>
