<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Abrir Chamado</h1>
</div>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <form id="novoChamado" action="atendimento/chamado/abrir" method="post">
                    <div class="toast-message" role="alert"></div>
                    <input type="hidden" name="csrfToken" value="<?= $_SESSION['csrfToken']; ?>">
                    <input type="hidden" name="fkCliente" value="<?= $_SESSION['loggedUserId']; ?>">
                    <div class="form-row">
                        <div class="form-group col-md-6 mb-3">
                            <label for="fkMotivoChamado">Motivo:</label>
                            <select class="form-control" id="fkMotivoChamado" name="fkMotivoChamado" required>
                                <option value="">Selecione...</option>
                                <option value="1">Cobrança/Fatura</option>
                                <option value="2">Defeito</option>
                                <option value="3">Desistência da compra</option>
                                <option value="4">Promoção</option>
                                <option value="5">Entrega</option>
                            </select>
                            <div class="invalid-feedback hidden">
                                Por favor selecione um motivo.
                            </div>
                        </div>
                        <div class="form-group col-md-6 mb-3">
                            <label for="fkTipoChamado">Tipo:</label>
                            <select class="form-control" id="fkTipoChamado" name="fkTipoChamado" required>
                                <option value="">Selecione...</option>
                                <option value="1">Informação</option>
                                <option value="2">Reclamação</option>
                                <option value="3">Solicitação</option>
                                <option value="4">Sugestão</option>
                                <option value="5">Elogio</option>
                            </select>
                            <div class="invalid-feedback hidden">
                                Por favor selecione um tipo.
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12 mb-6">
                            <label for="mensagem">Mensagem:</label>
                            <textarea name="mensagem" class="form-control" rows="8" id="mensagem" required></textarea>
                            <div class="invalid-feedback hidden">
                                Por favor escreva a mensagem.
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12 mb-6 text-center">
                            <button class="btn btn-info btn-block btn-sm" type="submit">Inserir Chamado</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>