<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"><?= $this->sLabel; ?></h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <?php if ($_SESSION['loggedUserType'] !== CLIENTE) : ?>
            <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Compartilhar</button>
                <button class="btn btn-sm btn-outline-secondary">Exportar</button>
            </div>
            <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                Esta semana
            </button>
        <?php else : ?>
            <a class="btn btn-sm btn-outline-secondary" href="atendimento/chamado/abrir" role="button">
                <span data-feather="mail"></span>
                Abrir Chamado
            </a>
        <?php endif; ?>
    </div>
</div>
<?php if (count($this->aChamados)) : ?>
    <div class="table-responsive">
        <table class="table table-striped table-sm table-hover table-borderless">
            <thead>
                <tr>
                    <th class="text-center" scope="col">Código</th>
                    <th scope="col">Data da Abertura</th>
                    <th scope="col">Motivo</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Mensagem</th>
                    <th scope="col">Status</th>
                    <?php if ($this->iTipo == 1000 || $this->iTipo == 1003) : ?>
                        <th scope="col">Data da Conclusão</th>
                    <?php endif; ?>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->aChamados as $oChamado) : ?>
                    <tr>
                        <th class="text-center" scope="row"><?= $oChamado->pkChamado; ?></th>
                        <td><?= date_format(date_create($oChamado->dataHoraAbertura), "d/m/Y H:i"); ?></td>
                        <td><?= $oChamado->motivo; ?></td>
                        <td><?= $oChamado->tipo; ?></td>
                        <td><?= $oChamado->mensagem; ?></td>
                        <td><?= $_SESSION['loggedUserType'] === CLIENTE && ($oChamado->status == 'Novo' || $oChamado->status == 'Atribuído') ? 'Em Aberto' : $oChamado->status; ?></td>
                        <?php if ($this->iTipo == 1000 || $this->iTipo == 1003) : ?>
                            <td><?= ! empty($oChamado->dataHoraFechamento) ? date_format(date_create($oChamado->dataHoraFechamento), "d/m/Y H:i") : '-'; ?></td>
                        <?php endif; ?>
                        <td>
                            <a class="btn btn-info btn-block btn-sm" href="atendimento/chamado/detalhes/<?= $oChamado->pkChamado; ?>" role="button">
                                <span data-feather="layers"></span>
                                Detalhes
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <br/>
<?php endif; ?>